# Generated by Django 5.0.6 on 2024-07-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0004_alter_yogacontents_thumnails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogacontents',
            name='thumnails',
            field=models.ImageField(default='/default.jpg', upload_to='media/yoga/%Y/%m/%d'),
        ),
    ]
