# Generated by Django 5.0.6 on 2024-07-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditate', '0004_rename_thumnails_meditatecontents_thumbnails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meditatecontents',
            name='thumbnails',
            field=models.ImageField(default='/default.jpg', upload_to='media/meditate/%Y/%m/%d'),
        ),
    ]
