# Generated by Django 5.0.6 on 2024-07-14 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meditate', '0003_meditatecontents_thumnails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meditatecontents',
            old_name='thumnails',
            new_name='thumbnails',
        ),
    ]
